language: go
go:
- 1.x
sudo: required
services:
- docker
env:
- GOVERSION=1.9
- GOVERSION=1.10
install: true
cache:
  timeout: 1000
  directories:
  - ~/.cache
script:
- ./run_tests.sh $GOVERSION
notifications:
  slack:
    rooms:
      secure: chvqsi7kPis2ZbF+cmqIYZ6W6OAO0rGySLxb7LYt6GXNa1zmrVb9Q60qpoMcpCxcV9NbMrnPu3zntsmqzipRfkuTqPY+WCY1L+Wq1vLU2PuZFmCGAo1892XanJt3aOhy/O7gBd8MpYRKVjFn9iRi9BFsiEiV0nXjH6QQ+RSB63vFLChfgIGhpIe50bGkHNanFUeFjcrKnThouVnbmnGnRUU5vBiiWmqP0P1DVpV16TOznTpPl2aODp18h1ew5Y82XLuq3pdbC4H4oq5+nwqDWWV+9HyGzsdn4QqWOMbRIRzmzsf4gWHoIgmHKKDxFD9QEd2PchpkcX0EGqtRyS9DDBSQK8genSN5fmbQPLzq8cLHMBPPuhL3lWu49LxlOrEGchsuY2pzmOs60Z6VEOJOHvSz2vV1tQRb7g24lzpVGt30QiiU4Klc9QFgwbdykYpk7L9ohou7yELZbR0WFNqvUJs61Mq2AzNWK5zuO6d2zAQ32qP8XH/6Pi+R4S/iaspwqlnNjwkspGwECWuxX31FyaSNmwtRKmdDGOg2a6RmN+A5fplp8k7jOre+nA3Zduc9oz0OnLZzwa37hocUoEx9NWmI5ke4NkPnnXfDa0RGubmFa2QtlHksTMhdfcevSAEwTvawCT+BZU/33+FcWERmsC6bX4qbGdgueSIoDeikeCM=
